name: build-page
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install python
      run:  uv python install 3.13

    - name: Build Page
      run:  make

    - name: Stage assets
      run:  |
        mkdir _site
        mv index.html _site
        cp -r css _site/
        cp -r images _site/
        cp -r fonts _site/

    - name: Upload Site Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
